export const CONCEPT_LABELS: Record<string, string> = {
    open_raise: "Open Raise",
    three_bet: "3-Bet",
    cold_call: "Cold Call",
    squeeze: "Squeeze",
    steal: "Steal",
    cbet_value: "Value C-Bet",
    cbet_bluff: "Bluff C-Bet",
    check_raise: "Check-Raise",
    float: "Float",
    probe: "Probe Bet",
    barrel: "Barrel",
    pot_control: "Pot Control",
    semi_bluff: "Semi-Bluff",
    check_call: "Check-Call",
    value_bet_thin: "Thin Value Bet",
    bluff_catch: "Bluff Catch",
    river_raise: "River Raise",
    river_bluff: "River Bluff",
};
